version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: "@testing-library/user-event"
    versions:
    - 12.6.2
    - 12.6.3
    - 12.7.0
    - 12.7.1
    - 12.7.2
    - 12.7.3
    - 12.8.0
    - 12.8.1
    - 12.8.3
    - 13.0.0
    - 13.0.1
    - 13.0.10
    - 13.0.14
    - 13.0.16
    - 13.0.2
    - 13.0.7
    - 13.0.8
    - 13.1.0
    - 13.1.1
    - 13.1.2
    - 13.1.3
    - 13.1.4
    - 13.1.5
  - dependency-name: sweetalert2
    versions:
    - 10.14.0
    - 10.14.1
    - 10.15.0
    - 10.15.1
    - 10.15.2
    - 10.15.5
    - 10.15.6
    - 10.15.7
    - 10.16.0
    - 10.16.1
    - 10.16.2
    - 10.16.4
    - 10.16.5
  - dependency-name: react-tooltip
    versions:
    - 4.2.13
    - 4.2.14
    - 4.2.15
    - 4.2.17
  - dependency-name: "@testing-library/jest-dom"
    versions:
    - 5.11.10
    - 5.11.9
  - dependency-name: react-redux
    versions:
    - 7.2.2
    - 7.2.3
  - dependency-name: socket.io-client
    versions:
    - 3.1.0
    - 3.1.1
    - 3.1.2
    - 4.0.0
  - dependency-name: react-device-detect
    versions:
    - 1.15.0
    - 1.16.0
  - dependency-name: react-scripts
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: "@testing-library/react"
    versions:
    - 11.2.3
    - 11.2.4
    - 11.2.5
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: elliptic
    versions:
    - 6.5.3
